models/Client.php
<?php

namespace app\models;
use yii\behaviors\TimestampBehavior;
use yii\web\UploadedFile;

/**
 * This is the model class for table "client".
 *
 * @property int $id
 * @property string $name
 * @property string $phone
 * @property int $nds
 * @property int $city_id
 * @property string $text
 * @property int $logo_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property City $city
 * @property Files $logo
 */
class Client extends \yii\db\ActiveRecord
{

  /**
   * @var UploadedFile
   */
  public $clientLogo;

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'client';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
      [['name', 'phone', 'city_id'], 'required'],
      [['nds', 'city_id', 'created_at', 'updated_at'], 'integer'],
      [['text', 'phone'], 'string'],
      [['name'], 'string', 'max' => 128],
      ['phone', 'match', 'pattern' => '/^\+7 \(\d{3}\) \d{3} \d{2} \d{2}$/',
        'message' => 'Телефон должен быть в формате +7 (XXX) XXX XX XX'],
      [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => City::className(), 'targetAttribute' => ['city_id' => 'id']],
      [['logo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Files::className(), 'targetAttribute' =>
        ['logo_id' => 'id']],
      [['clientLogo'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg'],
    ];
  }

  public function behaviors()
  {
    return [
      TimestampBehavior::class,
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'name' => 'Name',
      'phone' => 'Phone',
      'nds' => 'Nds',
      'city_id' => 'City',
      'text' => 'Text',
      'logo_id' => 'Logo',
      'created_at' => 'Created At',
      'updated_at' => 'Updated At',
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCity()
  {
    return $this->hasOne(City::className(), ['id' => 'city_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getLogo()
  {
    return $this->hasOne(Files::className(), ['id' => 'logo_id']);
  }

  /**
   * {@inheritdoc}
   * @return ClientQuery the active query used by this AR class.
   */
  public static function find()
  {
    return new ClientQuery(get_called_class());
  }

  public function uploadClientLogo()
  {
    if ($this->clientLogo instanceof UploadedFile) {
      $this->clientLogo->saveAs('uploads/img/' . $this->clientLogo->name);
      $model = new Files();
      $model->name = $this->clientLogo->name;
      $model->size = $this->clientLogo->size;
      if ($model->save(false)) {
        $model->link('clients', $this);
      }
      return true;
    } else {
      return false;
    }
  }
}

controllers/ClientController.php
<?php

namespace app\controllers;

use app\models\City;
use Yii;
use app\models\Client;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
  /**
   * {@inheritdoc}
   */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }

  /**
   * Lists all Client models.
   * @return mixed
   */
  public function actionIndex()
  {
    $dataProvider = new ActiveDataProvider([
      'query' => Client::find(),
    ]);

    return $this->render('index', [
      'dataProvider' => $dataProvider,
    ]);
  }


  /**
   * Generates cities list for client
   * @param null $q input phrase
   * @param null $id city.id
   * @return array
   */
  public function actionCityList($q = null, $id = null)
  {
    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '', 'region' => '']];
    if (!is_null($q)) {
      $query = new Query;
      $query->select('city.id, city.name AS text, region.name AS region')
        ->from('city')
        ->where(['rlike', 'city.name', '^' . ucfirst($q)])
        ->join('LEFT JOIN', 'region', 'region.id = city.region_id')
        ->limit(20);
      $data = $query->all();
      $out['results'] = array_values($data);
    } elseif ($id > 0) {
      $city = City::findOne($id);
      $out['results'] = ['id' => $id, 'text' => $city->name, 'region' => $city->region->name];
    }
    return $out;
  }

  /**
   * Displays a single Client model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionView($id)
  {
    return $this->render('view', [
      'model' => $this->findModel($id),
    ]);
  }

  /**
   * Creates a new Client model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    $model = new Client();
    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      $model->clientLogo = UploadedFile::getInstance($model, 'clientLogo');

      $model->uploadClientLogo();
      return $this->redirect(['view', 'id' => $model->id]);
    }
    return $this->render('create', [
      'model' => $model,
    ]);
  }

  /**
   * Updates an existing Client model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionUpdate($id)
  {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      $model->clientLogo = UploadedFile::getInstance($model, 'clientLogo');
      $model->uploadClientLogo();
      return $this->redirect(['view', 'id' => $model->id]);
    }

    return $this->render('update', [
      'model' => $model,
    ]);
  }

  /**c
   * Deletes an existing Client model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionDelete($id)
  {
    $this->findModel($id)->delete();

    return $this->redirect(['index']);
  }

  /**
   * Finds the Client model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Client the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = Client::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException('The requested page does not exist.');
  }
}

controllers/FilesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Files;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FilesController implements the CRUD actions for Files model.
 */
class FilesController extends Controller
{
  /**
   * {@inheritdoc}
   */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }

  /**
   * Lists all Files models.
   * @return mixed
   */
  public function actionIndex()
  {
    $dataProvider = new ActiveDataProvider([
      'query' => Files::find(),
    ]);

    return $this->render('index', [
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single Files model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionView($id)
  {
    return $this->render('view', [
      'model' => $this->findModel($id),
    ]);
  }

  /**
   * Creates a new Files model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    $model = new Files();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    }

    return $this->render('create', [
      'model' => $model,
    ]);
  }

  /**
   * Updates an existing Files model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionUpdate($id)
  {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    }

    return $this->render('update', [
      'model' => $model,
    ]);
  }

  /**
   * Deletes an existing Files model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionDelete($id)
  {
    $model = $this->findModel($id);
    if (file_exists('uploads/img/' . $model->name)) {
      unlink('uploads/img/' . $model->name);
    }
    $model->delete();
    return $this->goBack();
  }

  /**
   * Finds the Files model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Files the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = Files::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException('The requested page does not exist.');
  }
}

views/client/_form.php
<?php

use kartik\select2\Select2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-form">

  <?php
  $form = ActiveForm::begin(); ?>

  <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

  <?= $form->field($model, 'phone')->textInput() ?>

  <?= $form->field($model, 'nds')->checkbox() ?>

  <?php
  $url = \yii\helpers\Url::to(['city-list']);
  $cityName = empty($model->city_id) ? '' : $model->city->name . ', ' . $model->city->region->name;
  echo $form->field($model, 'city_id')->widget(Select2::className(), [
    'name' => 'city',
    'initValueText' => $cityName,
    'options' => ['placeholder' => 'Enter a city'],
    'language' => 'ru',
    'pluginOptions' => [
      'allowClear' => true,
      'minimumInputLength' => 1,
      'ajax' => [
        'url' => $url,
        'dataType' => 'json',
        'data' => new JsExpression('function(params) { return {q:params.term}; }')
      ],
      'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
      'templateResult' => new JsExpression('function(city) { return city.text + ", " + city.region; }'),
      'templateSelection' => new JsExpression('function (city) { return city.text; }'),
    ],
  ]); ?>

  <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

  <?php
  if (!empty($model->logo_id)) {
    echo Html::img('@web/uploads/img/' . $model->logo->name, ['style' => 'width:200px']);
    echo Html::a('X', ['files/delete', 'id' => $model->logo_id], [
      'data' => [
        'confirm' => 'Вы уверены что хотите удалить лого?'
      ],
    ]);
  }
  echo $form->field($model, 'clientLogo')->fileInput(['class' => 'custom-file-input']); ?>

	<div class="form-group">
    <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
	</div>

  <?php ActiveForm::end(); ?>

</div>

views/client/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = 'Create Client';
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/client/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Clients';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Client', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'phone',
            'nds',
            'city_id',
            'text:ntext',
            'logo_id',
            'created_at:datetime',
            'updated_at:datetime',

            ['class' => 'yii\grid\ActionColumn',
							'template' => '{update} {delete}'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/client/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = 'Update Client: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="client-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/client/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="client-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'phone',
            'nds',
            'city_id',
            'text:ntext',
            'logo_id',
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]) ?>

</div>